ARG _TAG=11.0.10_9-jdk-hotspot-focal
FROM adoptopenjdk:${_TAG}
# https://hub.docker.com/_/adoptopenjdk
# https://github.com/docker-library/docs/blob/master/adoptopenjdk/README.md#supported-tags-and-respective-dockerfile-links




# 
# ### OS Prepare
# # Setting timezone
# RUN apk --update add tzdata && \
#     cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
#     apk del tzdata && \
#     rm -rf /var/cache/apk/*
