FROM ubuntu:xenial

RUN apt-get update
RUN apt-get -y upgrade

# RUN apt-get -y install cmatrix
# RUN apt-get -y install sl

# RUN curl -sL https://deb.nodesource.com/setup | bash -
# RUN apt-get -y install nodejs
# RUN apt-get -y install build-essential
# RUN apt-get -y install npm
