ARG _TAG=15.0.2_7-jdk-openj9-0.24.0-focal
FROM adoptopenjdk:${_TAG}
# https://hub.docker.com/_/adoptopenjdk
# https://github.com/docker-library/docs/blob/master/adoptopenjdk/README.md#supported-tags-and-respective-dockerfile-links




# 
# ### OS Prepare
# # Setting timezone
# RUN apk --update add tzdata && \
#     cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
#     apk del tzdata && \
#     rm -rf /var/cache/apk/*
