# ref: https://gist.github.com/iganari/0b8bbd80c3bcf64581ba786217059c6d

name: 'push-cld-gcloud'

on:
  push:
    branches:
      - main
      - 'feature/add-dockerhub-to-githubactions'
      # - 'feature/hogehoge'
      # - develop

jobs:
  step:
    name: Update readme branch
    runs-on: ubuntu-20.04
    steps:
      - name: push
        shell: bash
        # env:
        #   iganari_dev_user: ${{ secrets.IGANARI_DEV_USER }}
        #   iganari_dev_email: ${{ secrets.IGANARI_DEV_EMAIL }}
        #   iganari_dev_token: ${{ secrets.IGANARI_DEV_TOKEN }}
        run: |
          docker version
          # cd /tmp
          # echo "Git Clone ${GITHUB_REPOSITORY}"
          # git clone https://${iganari_dev_token}@github.com/${GITHUB_REPOSITORY}.git
          # cd $(echo ${GITHUB_REPOSITORY} | awk -F\/ '{print $2}')
          # git config user.name "${iganari_dev_user}"
          # git config user.email "${iganari_dev_email}"
          # git checkout modify-readme-only
          # git pull origin $(echo ${GITHUB_REF} | sed 's/refs\/heads\///g') --no-edit
          # git push origin modify-readme-only
