name: Update Contanier Image on Docker Hub

on:
  push:
    branches:
      - main
      # - 'feature/hogehoge'

jobs:
  step:
    name: Push Contanier Image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Update iganarix/cld-gcloud
        env:
          docker_hub_user:   iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 50_cloud/gcloud --tag iganarix/cld-gcloud
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/cld-gcloud
      - name: Update iganarix/cld-gcloud-debian
        env:
          docker_hub_user:   iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 50_cloud/gcloud --tag iganarix/cld-gcloud-debian
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/cld-gcloud-debian
      - name: Update iganarix/os-alpine
        env:
          docker_hub_user:   iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 30_os/alpine --tag iganarix/os-alpine
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/os-alpine
      - name: Delete stored data
        run: rm -f /home/runner/.docker/config.json
