name: Update Contanier Image on Docker Hub

on:
  push:
    branches:
      - main
      - 'feature/modify-gcloud'
      # - 'feature/hogehoge'

jobs:
  step:
    name: Push Contanier Image
    runs-on: ubuntu-20.04
    timeout-minutes: 60 # job全体
    steps:

      - name: Check out repository code
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}

      - name: Set Tags date
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m%d-%H%M')" >> $GITHUB_ENV


      - name: Build iganarix/cld-gcloud
        timeout-minutes: 20 # step個別
        # env:
        #   docker_hub_user: iganarix
        #   docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: |
          cd 50_cloud/gcloud
          export _gcloud_version=$(cat _gcloud_version | head -n 1)

          sed -e "s/_GCLOUD_VERSION/${_gcloud_version}/g" Dockerfile-alpine.tpl > Dockerfile-alpine
          sed -e "s/_GCLOUD_VERSION/${_gcloud_version}/g" Dockerfile-debian.tpl > Dockerfile-debian

          docker build . --file Dockerfile-alpine --tag iganarix/cld-gcloud:${_gcloud_version}-alpine --tag iganarix/cld-gcloud:latest
          docker build . --file Dockerfile-debian --tag iganarix/cld-gcloud:${_gcloud_version}-debian
          # docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          # docker push iganarix/cld-gcloud:latest
          # docker push iganarix/cld-gcloud:${{ env.CURRENT_DATETIME }}

      - name: Upload iganarix/cld-gcloud
        timeout-minutes: 20 # step個別
        env:
          docker_hub_user: iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: |
          docker images
          echo 'debug 1'
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          echo 'debug 2'
          docker push iganarix/cld-gcloud:${_gcloud_version}-alpine
          echo 'debug 3'
          docker push iganarix/cld-gcloud:${_gcloud_version}-debian
          echo 'debug 4'
          docker push iganarix/cld-gcloud:latest

      - name: Update iganarix/os-alpine
        timeout-minutes: 20 # step個別
        env:
          docker_hub_user: iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 30_os/alpine --tag iganarix/os-alpine:latest --tag iganarix/os-alpine:${{ env.CURRENT_DATETIME }}
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/os-alpine:latest
          docker push iganarix/os-alpine:${{ env.CURRENT_DATETIME }}

      - name: Delete stored data
        run: rm -f /home/runner/.docker/config.json
