name: Update Contanier Image on Docker Hub

on:
  push:
    branches:
      - main
      - 'feature/modidy-github-actions'
      # - 'feature/hogehoge'

jobs:
  step:
    name: Push Contanier Image
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Set Tags date
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV


      - name: Update iganarix/cld-gcloud
        env:
          docker_hub_user: iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 50_cloud/gcloud --tag iganarix/cld-gcloud:latest --tag iganarix/cld-gcloud:${{ env.CURRENT_DATETIME }}
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/cld-gcloud:latest
          docker push iganarix/cld-gcloud:${{ env.CURRENT_DATETIME }}

      - name: Update iganarix/cld-gcloud-debian
        env:
          docker_hub_user: iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 50_cloud/gcloud-debian --tag iganarix/cld-gcloud-debian:latest --tag iganarix/cld-gcloud-debian:${{ env.CURRENT_DATETIME }}
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/cld-gcloud-debian:latest
          docker push iganarix/cld-gcloud-debian:${{ env.CURRENT_DATETIME }}

      - name: Update iganarix/os-alpine
        env:
          docker_hub_user: iganarix
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 30_os/alpine --tag iganarix/os-alpine:latest --tag iganarix/os-alpine:${{ env.CURRENT_DATETIME }}
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/os-alpine:latest
          docker push iganarix/os-alpine:${{ env.CURRENT_DATETIME }}

      - name: Delete stored data
        run: rm -f /home/runner/.docker/config.json
