name: 'push-cld-gcloud'

on:
  push:
    branches:
      - main
      - 'feature/add-dockerhub-to-githubactions'
      # - 'feature/hogehoge'

jobs:
  step:
    name: Update Contanier Image on Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Push Docker Hub
        env:
          docker_hub_user:   ${{ secrets.DOCKER_HUB_USER }}
          docker_hub_passwd: ${{ secrets.DOCKER_HUB_PASSWD }}
        run: | 
          docker build 50_cloud/gcloud --tag iganarix/cld-gcloud
          docker login -u ${docker_hub_user} -p ${docker_hub_passwd}
          docker push iganarix/cld-gcloud

